name: Publish VS Code Extension

on:
  release:
    types:
        - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npm run compile

    - name: Package Extension
      run: npm run build

    - name: Get Extension Filename
      id: get_filename
      run: echo "filename=$(ls *.vsix)" >> $GITHUB_OUTPUT

    - name: Upload Extension to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${{ steps.get_filename.outputs.filename }}
        asset_name: ${{ steps.get_filename.outputs.filename }}
        asset_content_type: application/zip

    - name: Publish Extension
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: npm run deploy
